### PR TITLE
fix breaking parse error

### PR DESCRIPTION
**Pull request by TrueType**
the v0.4.1 thows an exception right after installation. please provide an updated v0.4.2. thx

### CODE REVIEW

**Comment by w010** [comment]
Thank you, I will check this in a moment

**Review by w010 — APPROVED** [review]

**Comment by w010** [comment]
Wow that's a stupid mistake! I wonder how that even happen this version went to the repo.
Thanks again for the fix

**Comment by w010** [comment]
0.4.2 is online.
If you find any other problems please let me know.

**Comment by TrueType** [comment]
u r welcome. I had class loading problems updating 0.3. to 0.4. Only after deinstall and reinstall the extension they vanished. On TYPO3v7.6. Just as some background information.

**Pull request merged**
